git @startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class Main #grey
    Class Commons LOGIC_COLOR_T2
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


UI -[#006400]> Logic
UI -right[#006400]-> Model
Logic -[#1E90FF]-> Storage
Logic -down[#1E90FF]-> Model
Main -[#A9A9A9]-> UI
Main -[#A9A9A9]-> Logic
Main -[#A9A9A9]-> Storage
Main -up[#A9A9A9]-> Model
Main -down[hidden]-> Commons

Storage -up[STORAGE_COLOR].> Model
Storage .right[STORAGE_COLOR].>File
User ..> UI
@enduml
