@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HouseholdBookParser" as HouseholdBookParser LOGIC_COLOR
participant ":DeleteHouseholdCommandParser" as DeleteHouseholdCommandParser LOGIC_COLOR
participant "d:DeleteHouseholdCommand" as DeleteHouseholdCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":JsonHouseholdBookStorage" as JsonHouseholdBookStorage STORAGE_COLOR
end box

[-> LogicManager : execute("delete-household id/H000001")
activate LogicManager

LogicManager -> HouseholdBookParser : parseCommand("delete-household id/H000001")
activate HouseholdBookParser

create DeleteHouseholdCommandParser
HouseholdBookParser -> DeleteHouseholdCommandParser
activate DeleteHouseholdCommandParser

DeleteHouseholdCommandParser --> HouseholdBookParser
deactivate DeleteHouseholdCommandParser

HouseholdBookParser -> DeleteHouseholdCommandParser : parse("id/H000001")
activate DeleteHouseholdCommandParser

create DeleteHouseholdCommand
DeleteHouseholdCommandParser -> DeleteHouseholdCommand
activate DeleteHouseholdCommand

DeleteHouseholdCommand --> DeleteHouseholdCommandParser :
deactivate DeleteHouseholdCommand

DeleteHouseholdCommandParser --> HouseholdBookParser : d
deactivate DeleteHouseholdCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteHouseholdCommandParser -[hidden]-> HouseholdBookParser
destroy DeleteHouseholdCommandParser

HouseholdBookParser --> LogicManager : d
deactivate HouseholdBookParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
HouseholdBookParser -[hidden]-> LogicManager
destroy HouseholdBookParser

LogicManager -> DeleteHouseholdCommand : execute(m)
activate DeleteHouseholdCommand

DeleteHouseholdCommand -> DeleteHouseholdCommand : showConfirmationDialog(household)
activate DeleteHouseholdCommand
DeleteHouseholdCommand --> DeleteHouseholdCommand : true
deactivate DeleteHouseholdCommand


DeleteHouseholdCommand -> Model : removeHousehold(H000001)
activate Model

Model --> DeleteHouseholdCommand

create CommandResult
DeleteHouseholdCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteHouseholdCommand
deactivate CommandResult
'Hidden arrow to position the destroy marker below the end of the activation bar.
CommandResult -[hidden]-> DeleteHouseholdCommand
destroy CommandResult

DeleteHouseholdCommand --> LogicManager : r
deactivate DeleteHouseholdCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteHouseholdCommand -[hidden]-> LogicManager
destroy DeleteHouseholdCommand

LogicManager -> Model : getHouseholdBook()
Model -> JsonHouseholdBookStorage : saveHouseholdBook()

activate JsonHouseholdBookStorage
'JsonHouseholdBookStorage --> Model'
deactivate JsonHouseholdBookStorage
'Hidden arrow to position the destroy marker below the end of the activation bar.
JsonHouseholdBookStorage -[hidden]-> Model
destroy JsonHouseholdBookStorage

'Model --> LogicManager'
deactivate Model
'Hidden arrow to position the destroy marker below the end of the activation bar.
Model -[hidden]-> LogicManager
destroy Model

[<--LogicManager : r
deactivate LogicManager
'Hidden arrow to position the destroy marker below the end of the activation bar.
LogicManager -[hidden]-> HouseholdBookParser
destroy LogicManager

@enduml
