@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic <<Rectangle>> {
  class "<<interface>>\nLogic" as Logic
  class LogicManager
  class Messages

  Logic <|.. LogicManager
}

package "logic.commands" <<Rectangle>> {
  class "{abstract}\nCommand" as Command
  class AddHouseholdCommand
  class AddSessionCommand
  class ClearCommand
  class CommandResult
  class DeleteHouseholdCommand
  class DeleteSessionCommand
  class EditHouseholdCommand
  class EditSessionCommand
  class ExitCommand
  class FindHouseholdCommand
  class HelpCommand
  class ListHouseholdsCommand
  class ViewFullSessionCommand
  class ViewHouseholdSessionsCommand

  Command <|-- AddHouseholdCommand
  Command <|-- AddSessionCommand
  Command <|-- ClearCommand
  Command <|-- DeleteHouseholdCommand
  Command <|-- DeleteSessionCommand
  Command <|-- EditHouseholdCommand
  Command <|-- EditSessionCommand
  Command <|-- ExitCommand
  Command <|-- FindHouseholdCommand
  Command <|-- HelpCommand
  Command <|-- ListHouseholdsCommand
  Command <|-- ViewFullSessionCommand
  Command <|-- ViewHouseholdSessionsCommand
}

package "logic.commands.exceptions" <<Rectangle>> {
  class CommandException

  CommandException --|> Exception
}

package "logic.parser" <<Rectangle>> {
  class "<<interface>>\nParser<T extends Command>" as Parser
  class AddHouseholdCommandParser
  class AddSessionCommandParser
  class ArgumentMultimap
  class ArgumentTokenizer
  class CliSyntax
  class DeleteHouseholdCommandParser
  class DeleteSessionCommandParser
  class EditHouseholdCommandParser
  class EditSessionCommandParser
  class FindHouseholdCommandParser
  class HouseholdBookParser
  class ParserUtil
  class Prefix
  class SessionIdentifier
  class SessionParserUtil
  class ViewFullSessionCommandParser
  class ViewHouseholdSessionsCommandParser

  Parser <|.. AddHouseholdCommandParser
  Parser <|.. AddSessionCommandParser
  Parser <|.. DeleteHouseholdCommandParser
  Parser <|.. DeleteSessionCommandParser
  Parser <|.. EditHouseholdCommandParser
  Parser <|.. EditSessionCommandParser
  Parser <|.. FindHouseholdCommandParser
  Parser <|.. ViewFullSessionCommandParser
  Parser <|.. ViewHouseholdSessionsCommandParser
}

package "logic.parser.exceptions" <<Rectangle>> {
  class ParseException

  ParseException --|> IllegalValueException
}

' Logical links (optional layout ordering)
AddHouseholdCommandParser ..> AddHouseholdCommand : parses >
ViewFullSessionCommandParser ..> ViewFullSessionCommand : parses >

LogicManager --> CommandResult
LogicManager --> Parser
LogicManager --> Messages

@enduml