@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>> {
class "<<interface>> ReadOnlyUserPrefs" as ReadOnlyUserPrefs
class "<<interface>> ReadOnlyHouseholdBook" as ReadOnlyHouseholdBook
class "<<interface>> Model" as Model
class UserPrefs
class HouseholdBook
class ModelManager
class Tag
class Address
class Contact
class Household
class HouseholdContainsKeywordsPredicate
class HouseholdId
class Name
class Session
class SessionDate
class SessionNote
class SessionTime

' Inheritance relationships
UserPrefs .up.|> ReadOnlyUserPrefs
HouseholdBook .up.|> ReadOnlyHouseholdBook
ModelManager .up.|> Model
HouseholdContainsKeywordsPredicate .up.|> Household

' Associations from ModelManager (plain association)
ModelManager --> HouseholdBook
ModelManager --> UserPrefs

' Composition relationships (using solid diamond, no labels)
HouseholdBook *-- Household
HouseholdBook *-- Session

Household *-- Name
Household *-- Address
Household *-- Contact
Household *-- HouseholdId
Household *-- Session

' Non-composition association
Household --> Tag

' Composition in Session
Session *-- SessionDate
Session *-- SessionTime
Session *-- SessionNote

' Non-composition association
Session --> HouseholdId
Class I #FFFFFF
}
Class HiddenOutside #FFFFFF
HiddenOutside ..> Model


@enduml



