@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR_T4
skinparam classBackgroundColor STORAGE_COLOR

top to bottom direction

package storage <<Rectangle>> {

  ' Interfaces
  class "<<interface>>\nStorage" as Storage
  class "<<interface>>\nHouseholdBookStorage" as HouseholdBookStorage
  class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage

  ' Force Storage to stay at the top
  Storage -[hidden]-> StorageManager

  ' Interface inheritance
  HouseholdBookStorage <|-- Storage
  UserPrefsStorage <|-- Storage

  ' Implementing classes
  class "JsonHouseholdBookStorage"
  class "JsonUserPrefsStorage"
  class "StorageManager"

  HouseholdBookStorage <|.. JsonHouseholdBookStorage
  UserPrefsStorage <|.. JsonUserPrefsStorage
  Storage <|.. StorageManager

  ' Serialization-related classes
  class "JsonSerializableHouseholdBook"
  class "JsonAdaptedHousehold"
  class "JsonAdaptedSession"
  class JsonAdaptedTag

  JsonSerializableHouseholdBook --> JsonAdaptedHousehold
  JsonSerializableHouseholdBook --> JsonAdaptedSession
  JsonSerializableHouseholdBook --> JsonAdaptedTag

  StorageManager --> JsonHouseholdBookStorage
  StorageManager --> JsonUserPrefsStorage
}

@enduml
