@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedAddressBook" as VersionedAddressBook MODEL_COLOR
end box

[-> Model : undoAddressBook()
activate Model

Model -> VersionedAddressBook : undo()
activate VersionedAddressBook

VersionedAddressBook -> VersionedAddressBook :resetData(ReadOnlyAddressBook)
VersionedAddressBook --> Model :
deactivate VersionedAddressBook
VersionedAddressBook -[hidden]> VersionedAddressBook :
destroy VersionedAddressBook

[<-- Model
deactivate Model
Model -[hidden]> Model :
destroy Model
@enduml
