@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedHouseholdBook" as VersionedHouseholdBook MODEL_COLOR
end box

[-> Model : undoAddressBook()
activate Model

Model -> VersionedHouseholdBook : undo()
activate VersionedHouseholdBook

VersionedHouseholdBook -> VersionedHouseholdBook :resetData(ReadOnlyHouseholdBook)
VersionedHouseholdBook --> Model :
deactivate VersionedHouseholdBook
VersionedHouseholdBook -[hidden]> VersionedHouseholdBook :
destroy VersionedHouseholdBook

[<-- Model
deactivate Model
Model -[hidden]> Model :
destroy Model
@enduml
